# Use the official Node-RED image as the base
FROM nodered/node-red:latest

# Install additional Node-RED nodes for PostgreSQL and Serial Port
RUN npm install \
    node-red-contrib-postgresql \
    node-red-node-serialport